sudo: true
language: haskell

# http://docs.haskellstack.org/en/stable/travis_ci/#container-infrastructure
cache:
  directories:
    - $HOME/.stack
    - $HOME/.ghc
    - $TRAVIS_BUILD_DIR/.stack-work

before_install:
  - unset CC
  - mkdir -p ~/.local/bin
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --system-ghc --no-terminal --skip-ghc-check test

matrix:
  include:
  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: STACK_YAML="stack.yaml" GHCVER=8.6.5
    compiler: ": #stack default"
    addons: {apt: {packages: [ghc-8.6.5], sources: [hvr-ghc]}}
