sudo: false

# http://docs.haskellstack.org/en/stable/travis_ci/#container-infrastructure
cache:
  directories:
    - $HOME/.stack
    - $HOME/.ghc
    - $HOME/nix.store

matrix:
  include:
  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - language: c
    env: STACK_YAML="stack.yaml" GHCVER=8.2.2
    compiler: ": #stack default"
    addons: {apt: {packages: [ghc-8.2.2], sources: [hvr-ghc]}}
    before_install:
      - unset CC
      - mkdir -p ~/.local/bin
      - export PATH=/opt/ghc/$GHCVER/bin:$PATH
      - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

    script:
      - stack --system-ghc --no-terminal --skip-ghc-check test

  - language: nix
    before_install:
      - sudo mkdir -p /etc/nix
      - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
      - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

    before_cache:
      - mkdir -p $HOME/nix.store
      - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

    script:
      - nix-build -A gtfsschedule release.nix
